-- LEX TIGRESS: SUPABASE SCHEMA SETUP
-- Run this in Supabase Dashboard -> SQL Editor

-- 1. User Profiles Table
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT,
    display_name TEXT,
    avatar_url TEXT,
    role TEXT,
    search_limit INTEGER DEFAULT 50,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Cases Table
CREATE TABLE IF NOT EXISTS public.cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    diary_number TEXT NOT NULL,
    diary_year TEXT NOT NULL,
    cnr_number TEXT,
    case_number TEXT,
    case_type TEXT,
    status TEXT DEFAULT 'Pending',
    petitioner TEXT,
    respondent TEXT,
    display_title TEXT,
    next_hearing_date DATE,
    archived BOOLEAN DEFAULT FALSE,
    added_on TIMESTAMPTZ DEFAULT NOW(),
    last_viewed TIMESTAMPTZ DEFAULT NOW(),
    case_data JSONB DEFAULT '{}'::jsonb,
    
    -- Ensure a user can't track the same case twice
    UNIQUE (user_id, diary_number, diary_year)
);

-- 3. App State Table
CREATE TABLE IF NOT EXISTS public.user_app_state (
    user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    roles JSONB DEFAULT '[]'::jsonb,
    team_members JSONB DEFAULT '[]'::jsonb,
    training JSONB DEFAULT '[]'::jsonb,
    ai_stats JSONB DEFAULT '{}'::jsonb,
    doc_defect_history JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Ensure Columns Exist (in case tables were partially created)
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users;
ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS added_on TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS last_viewed TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS case_data JSONB DEFAULT '{}'::jsonb;

-- Drop obsolete or incorrect columns if they exist (clean up)
ALTER TABLE public.user_profiles DROP COLUMN IF EXISTS full_name;
ALTER TABLE public.user_app_state DROP COLUMN IF EXISTS state_data;

ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS roles JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS team_members JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS training JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS ai_stats JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS doc_defect_history JSONB DEFAULT '[]'::jsonb;

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_app_state ENABLE ROW LEVEL SECURITY;

-- ADD MISSING COLUMNS REQUIRED BY FORWARD-FACING FRONTEND
-- Required for unstructured eCourts data (listing history, timeline, scraped blobs)
ALTER TABLE public.cases ADD COLUMN IF NOT EXISTS case_data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.user_app_state ADD COLUMN IF NOT EXISTS doc_defect_history JSONB DEFAULT '[]'::jsonb;


-- User Profiles: Users can only read/update their own profile
CREATE POLICY "Users can view own profile" ON public.user_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.user_profiles FOR UPDATE USING (auth.uid() = id);

-- Cases: Users can only see their own cases
CREATE POLICY "Users can view own cases" ON public.cases FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own cases" ON public.cases FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own cases" ON public.cases FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own cases" ON public.cases FOR DELETE USING (auth.uid() = user_id);

-- App State: Users can only see their own app state
CREATE POLICY "Users can view own state" ON public.user_app_state FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own state" ON public.user_app_state FOR ALL USING (auth.uid() = user_id);
